// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCvZzUvdX-rcnUETil4_CvxM1I-H8yqtYg",
  authDomain: "builder-60ea6.firebaseapp.com",
  projectId: "builder-60ea6",
  storageBucket: "builder-60ea6.firebasestorage.app",
  messagingSenderId: "1006512259839",
  appId: "1:1006512259839:web:30d0356907777cb13cc2ca",
  measurementId: "G-DDMBF9TNEV"
  );

  static const FirebaseOptions android = FirebaseOptions(
   apiKey: "AIzaSyCvZzUvdX-rcnUETil4_CvxM1I-H8yqtYg",
  authDomain: "builder-60ea6.firebaseapp.com",
  projectId: "builder-60ea6",
  storageBucket: "builder-60ea6.firebasestorage.app",
  messagingSenderId: "1006512259839",
  appId: "1:1006512259839:web:30d0356907777cb13cc2ca",
  measurementId: "G-DDMBF9TNEV"
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQLJUhyhvAO8hBth4djJHALuzwBTsLTyY',
    appId: '1:128357506503:ios:06b1850ff92e9ab0134de2',
    messagingSenderId: '128357506503',
    projectId: 'builder-c3dab',
    storageBucket: 'builder-c3dab.appspot.com',
    iosClientId: '128357506503-gp73868lto3qtd9eevl45t7gjj8p8tmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.builder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQLJUhyhvAO8hBth4djJHALuzwBTsLTyY',
    appId: '1:128357506503:ios:06b1850ff92e9ab0134de2',
    messagingSenderId: '128357506503',
    projectId: 'builder-c3dab',
    storageBucket: 'builder-c3dab.appspot.com',
    iosClientId: '128357506503-gp73868lto3qtd9eevl45t7gjj8p8tmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.builder',
  );
}
